[local]
localhost

[mongodb]
mongodb-dev.phani.fun

[catalogue]
catalogue-dev.phani.fun

[redis]
redis-dev.phani.fun

[user]
user-dev.phani.fun

[cart]
cart-dev.phani.fun

[mysql]
mysql-dev.phani.fun

[shipping]
shipping-dev.phani.fun

[rabbitmq]
rabbitmq-dev.phani.fun

[payment]
payment-dev.phani.fun

[frontend]
frontend-dev.phani.fun
